# Generated by Django 5.2.17 on 2026-08-21 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('timezone', models.CharField(default='America/New_York', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Group owner'), ('admin', 'Group administrator'), ('moderator', 'Moderator'), ('game_manager', 'Game manager'), ('reader', 'Reader')], default='reader', max_length=20)),
                ('display_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_memberships', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.readinggroup')),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('late_entry_deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed'), ('finalized', 'Finalized'), ('archived', 'Archived')], default='draft', max_length=12)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_months', to='core.readinggroup')),
            ],
            options={
                'ordering': ['-starts_on'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('object_type', models.CharField(max_length=80)),
                ('object_id', models.CharField(blank=True, max_length=80)),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.readinggroup')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('color', models.CharField(default='#6d5dfc', max_length=7)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='core.challengemonth')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeamAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_assignments', to='core.challengemonth')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_assignments', to='core.membership')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.team')),
            ],
        ),
        migrations.CreateModel(
            name='BookSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=200)),
                ('book_format', models.CharField(choices=[('paperback', 'Paperback'), ('hardcover', 'Hardcover'), ('ebook', 'E-book'), ('audio', 'Audio'), ('manga', 'Manga'), ('fanfic', 'Fanfic'), ('other', 'Other')], max_length=16)),
                ('completed_on', models.DateField()),
                ('submitted_pages', models.PositiveIntegerField()),
                ('metadata_pages', models.PositiveIntegerField(blank=True, null=True)),
                ('approved_pages', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('review_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_book_submissions', to=settings.AUTH_USER_MODEL)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='core.challengemonth')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='core.membership')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('submitted_pages__gt', 0)), name='submitted_pages_positive'), models.CheckConstraint(condition=models.Q(('approved_pages__isnull', True), ('approved_pages__gt', 0), _connector='OR'), name='approved_pages_positive_or_null')],
            },
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('group', 'user'), name='unique_group_user_membership'),
        ),
        migrations.AddConstraint(
            model_name='challengemonth',
            constraint=models.UniqueConstraint(fields=('group', 'name'), name='unique_group_challenge_month'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('month', 'name'), name='unique_month_team'),
        ),
        migrations.AddConstraint(
            model_name='teamassignment',
            constraint=models.UniqueConstraint(fields=('month', 'participant'), name='one_team_per_participant_per_month'),
        ),
    ]
