# Generated by Django 5.2.17 on 2026-08-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_booksubmission_is_removed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readinggroup',
            name='join_code_hash',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='readinggroup',
            name='join_code_hint',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
