# Generated by Django 5.2.17 on 2026-08-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_readinggroup_join_code_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengemonth',
            name='team_stats_visibility',
            field=models.CharField(choices=[('everyone', 'Everyone in the group'), ('staff', 'Owners, administrators, and moderators'), ('owner', 'Group owners only')], default='owner', max_length=10),
        ),
    ]
