# Generated by Django 5.2.17 on 2026-08-21 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def enroll_existing_team_members(apps, schema_editor):
    TeamAssignment = apps.get_model('core', 'TeamAssignment')
    MonthEnrollment = apps.get_model('core', 'MonthEnrollment')
    enrollments = [
        MonthEnrollment(month_id=assignment.month_id, participant_id=assignment.participant_id)
        for assignment in TeamAssignment.objects.all().iterator()
    ]
    MonthEnrollment.objects.bulk_create(enrollments, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_challengemonth_team_stats_visibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('enrolled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_month_enrollments', to=settings.AUTH_USER_MODEL)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.challengemonth')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='month_enrollments', to='core.membership')),
            ],
            options={
                'ordering': ['participant__display_name'],
                'constraints': [models.UniqueConstraint(fields=('month', 'participant'), name='one_enrollment_per_participant_per_month')],
            },
        ),
        migrations.RunPython(enroll_existing_team_members, migrations.RunPython.noop),
    ]
