# Generated by Django 5.2.17 on 2026-08-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_monthenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='readinggroup',
            name='access_code_visibility',
            field=models.CharField(choices=[('owner', 'Group owners only'), ('staff', 'Owners, administrators, and moderators'), ('members', 'All group members')], default='owner', max_length=10),
        ),
        migrations.AddField(
            model_name='readinggroup',
            name='join_code',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
