# Generated by Django 5.2.17 on 2026-08-21 17:50

from django.db import migrations, models
from django.contrib.auth.hashers import make_password
import secrets


def generate_unique_codes(apps, schema_editor):
    ReadingGroup = apps.get_model("core", "ReadingGroup")
    alphabet = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"
    used = set()
    for group in ReadingGroup.objects.all().iterator():
        while True:
            code = "".join(secrets.choice(alphabet) for _ in range(6))
            if code not in used:
                used.add(code)
                break
        group.join_code = code
        group.join_code_hash = make_password(code)
        group.join_code_hint = code[-4:]
        group.save(update_fields=["join_code", "join_code_hash", "join_code_hint"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_readinggroup_access_code_visibility_and_more'),
    ]

    operations = [
        migrations.RunPython(generate_unique_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='readinggroup',
            name='join_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
