# Generated by Django 5.2.17 on 2026-08-21 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_readinggroup_join_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
