# Generated by Django 5.2.17 on 2026-08-22 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_team_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksubmission',
            name='reference_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='booksubmission',
            name='verification_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.CreateModel(
            name='CatalogBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=32)),
                ('provider_book_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=300)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('cover_url', models.URLField(blank=True, max_length=1000)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('refreshed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title', 'author'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_book_id'), name='unique_catalog_book_per_provider')],
            },
        ),
        migrations.AddField(
            model_name='booksubmission',
            name='catalog_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='core.catalogbook'),
        ),
        migrations.CreateModel(
            name='CatalogEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=32)),
                ('provider_edition_id', models.CharField(max_length=100)),
                ('isbn_10', models.CharField(blank=True, max_length=10)),
                ('isbn_13', models.CharField(blank=True, max_length=13)),
                ('format_name', models.CharField(blank=True, max_length=80)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('audio_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('refreshed_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='core.catalogbook')),
            ],
            options={
                'ordering': ['book__title', 'format_name', 'provider_edition_id'],
            },
        ),
        migrations.AddField(
            model_name='booksubmission',
            name='catalog_edition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='core.catalogedition'),
        ),
        migrations.AddConstraint(
            model_name='catalogedition',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_edition_id'), name='unique_catalog_edition_per_provider'),
        ),
    ]
