# Generated by Django 5.2.17 on 2026-08-22 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_booksubmission_reference_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksubmission',
            name='started_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
