# Generated by Django 5.2.17 on 2026-08-22 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_booksubmission_started_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardcoverConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_token', models.TextField()),
                ('token_hint', models.CharField(blank=True, max_length=4)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tested_at', models.DateTimeField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('last_error', models.CharField(blank=True, max_length=300)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hardcover_connection', to='core.readinggroup')),
            ],
        ),
    ]
