# Generated by Django 5.2.17 on 2026-08-22 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_catalogsearchcache'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksubmission',
            name='scoring_catalog_edition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scored_submissions', to='core.catalogedition'),
        ),
        migrations.AddField(
            model_name='booksubmission',
            name='verification_method',
            field=models.CharField(choices=[('manual', 'Manual Review'), ('hardcover', 'Hardcover Edition'), ('hardcover_audio', 'Hardcover Audio Equivalent')], default='manual', max_length=24),
        ),
        migrations.AddField(
            model_name='catalogedition',
            name='users_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
