# Generated by Django 5.2.17 on 2026-08-22 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='selected_avatar',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
