# Generated by Django 5.2.17 on 2026-08-22 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_userprofile_selected_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='permission_overrides',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
