# Generated by Django 5.2.17 on 2026-08-22 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_userprofile_must_change_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booksubmission',
            name='bonus_pages',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booksubmission',
            name='final_scored_pages',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MonthTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('bonus_pages', models.PositiveIntegerField(default=50)),
                ('allow_stacking', models.BooleanField(default=True, help_text='Allow this theme to be claimed with another theme on the same book.')),
                ('prompt', models.CharField(blank=True, help_text='Optional question readers must answer when claiming this theme.', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='core.challengemonth')),
            ],
            options={
                'ordering': ['starts_on', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ThemeClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=12)),
                ('approved_bonus_pages', models.PositiveIntegerField(default=0)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_theme_claims', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_claims', to='core.booksubmission')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='core.monththeme')),
            ],
            options={
                'ordering': ['theme__starts_on', 'theme__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='monththeme',
            constraint=models.UniqueConstraint(fields=('month', 'name'), name='unique_theme_name_per_month'),
        ),
        migrations.AddConstraint(
            model_name='themeclaim',
            constraint=models.UniqueConstraint(fields=('submission', 'theme'), name='unique_theme_claim_per_submission'),
        ),
    ]
