# Generated by Django 5.2.17 on 2026-08-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_backfill_final_scored_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengemonth',
            name='announcement',
            field=models.TextField(blank=True, help_text='Message displayed when Custom Announcement is selected.'),
        ),
        migrations.AddField(
            model_name='challengemonth',
            name='announcement_mode',
            field=models.CharField(choices=[('inherit', 'Use Group Announcement'), ('custom', 'Custom Announcement'), ('none', 'No Announcement')], default='inherit', max_length=10),
        ),
        migrations.AddField(
            model_name='readinggroup',
            name='announcement',
            field=models.TextField(blank=True, help_text='Optional message displayed on the group page.'),
        ),
    ]
