# Generated by Django 5.2.17 on 2026-08-22 14:38

from django.db import migrations, models


def enable_existing_announcements(apps, schema_editor):
    ReadingGroup = apps.get_model("core", "ReadingGroup")
    ReadingGroup.objects.exclude(announcement="").update(announcement_enabled=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_challengemonth_announcement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readinggroup',
            name='announcement_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(enable_existing_announcements, migrations.RunPython.noop),
    ]
