# Generated by Django 5.2.17 on 2026-08-23 20:59

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_platformbackupsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformbackupsettings',
            name='weekday',
        ),
        migrations.AddField(
            model_name='platformbackupsettings',
            name='weekdays',
            field=models.JSONField(default=core.models.default_backup_weekdays),
        ),
    ]
