# Generated by Django 5.2.17 on 2026-08-23 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_platformbackupsettings_weekday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformbackupsettings',
            name='last_error',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='platformbackupsettings',
            name='last_failure_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='platformbackupsettings',
            name='last_success_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
