# Generated by Django 5.2.17 on 2026-08-23

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_backup_operational_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("display_name", models.CharField(default="My Northbound", max_length=120)),
                ("timezone", models.CharField(default=core.models.default_platform_timezone, max_length=64)),
                ("allow_public_registration", models.BooleanField(default=True)),
                ("allow_user_group_creation", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
