# Generated by Django 5.2.17 on 2026-08-24 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_challengestaffassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengestaffassignment',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_assignments', to='core.team'),
        ),
        migrations.AlterField(
            model_name='challengestaffassignment',
            name='role',
            field=models.CharField(choices=[('host', 'Host'), ('team_leader', 'Team Leader')], default='host', max_length=20),
        ),
    ]
