# Generated by Django 5.2.17 on 2026-08-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_challengestaffassignment_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengestaffassignment',
            name='role',
            field=models.CharField(choices=[('host', 'Host'), ('team_leader', 'Team Leader'), ('floater', 'Floater')], default='host', max_length=20),
        ),
    ]
