# Generated by Django 5.2.17 on 2026-08-26 14:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_userprofile_discord_username_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengemonth',
            name='registration_answer_editing_hours',
            field=models.PositiveSmallIntegerField(default=24, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(720)]),
        ),
        migrations.AddField(
            model_name='challengemonth',
            name='registration_answer_editing_policy',
            field=models.CharField(choices=[('none', 'No editing after registration'), ('timed', 'Editing allowed for a set period'), ('until_close', 'Editing allowed until registration closes')], default='timed', max_length=12),
        ),
        migrations.CreateModel(
            name='ChallengeSignupQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wording', models.CharField(max_length=240)),
                ('question_type', models.CharField(choices=[('short_text', 'Short Text'), ('number', 'Number'), ('single_choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice')], max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('choices', models.JSONField(blank=True, default=list)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signup_questions', to='core.challengemonth')),
            ],
            options={
                'ordering': ['position', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeSignupAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(blank=True, default=str)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signup_answers', to='core.monthenrollment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='core.challengesignupquestion')),
            ],
            options={
                'ordering': ['question__position', 'question_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='challengesignupquestion',
            constraint=models.UniqueConstraint(fields=('month', 'position'), name='unique_signup_question_position'),
        ),
        migrations.AddConstraint(
            model_name='challengesignupanswer',
            constraint=models.UniqueConstraint(fields=('enrollment', 'question'), name='one_answer_per_signup_question'),
        ),
    ]
