# Generated by Django 5.2.17 on 2026-08-28 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_modifier_provenance(apps, schema_editor):
    BookSubmission = apps.get_model("core", "BookSubmission")
    ModifierProvenance = apps.get_model("core", "ModifierProvenance")
    ThemeClaim = apps.get_model("core", "ThemeClaim")

    approved_claims = ThemeClaim.objects.filter(
        status="approved",
        approved_bonus_pages__gt=0,
    ).select_related("submission", "theme")
    explained_by_submission = dict(
        approved_claims.values("submission_id")
        .annotate(total=models.Sum("approved_bonus_pages"))
        .values_list("submission_id", "total")
    )

    inconsistent = []
    approved_submissions = BookSubmission.objects.filter(status="approved").only(
        "id", "bonus_pages"
    )
    for submission in approved_submissions.iterator():
        explained = explained_by_submission.get(submission.pk, 0)
        if explained > submission.bonus_pages:
            inconsistent.append((submission.pk, submission.bonus_pages, explained))
    if inconsistent:
        examples = ", ".join(
            f"submission {pk}: bonus_pages={stored}, approved Theme claims={explained}"
            for pk, stored, explained in inconsistent[:10]
        )
        raise RuntimeError(
            "Modifier provenance backfill stopped because approved Theme claim snapshots "
            "exceed stored BookSubmission.bonus_pages. No historical scoring fields were "
            f"changed. Correct the inconsistent data and retry the migration. {examples}"
        )

    for claim in approved_claims.iterator():
        submission = claim.submission
        ModifierProvenance.objects.get_or_create(
            source_type="theme_bonus",
            source_reference=f"theme_claim:{claim.pk}",
            defaults={
                "month_id": submission.month_id,
                "participant_id": submission.participant_id,
                "submission_id": submission.pk,
                "source_label": claim.theme.name,
                "source_context": f"Migrated approved Theme claim {claim.pk}",
                "amount": claim.approved_bonus_pages,
                "effective_date": submission.completed_on,
                "applied_by_id": claim.reviewed_by_id,
                "applied_at": claim.reviewed_at,
                "is_system_generated": True,
                "is_active": True,
            },
        )

    for submission in approved_submissions.iterator():
        explained = explained_by_submission.get(submission.pk, 0)
        difference = submission.bonus_pages - explained
        if difference <= 0:
            continue
        ModifierProvenance.objects.get_or_create(
            source_type="legacy_modifier",
            source_reference=f"legacy_submission:{submission.pk}",
            defaults={
                "month_id": submission.month_id,
                "participant_id": submission.participant_id,
                "submission_id": submission.pk,
                "source_label": "Legacy Modifier",
                "source_context": (
                    "Migrated unexplained historical bonus difference; original source unknown."
                ),
                "amount": difference,
                "effective_date": submission.completed_on,
                "applied_by_id": None,
                "applied_at": submission.reviewed_at,
                "is_system_generated": True,
                "is_active": True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_challenge_role_visibility_audiences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModifierProvenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('theme_bonus', 'Theme bonus'), ('legacy_modifier', 'Legacy Modifier'), ('botm_book', 'Book of the Month book bonus'), ('botm_completion', 'Book of the Month completion bonus'), ('tbr_book', 'Personal TBR book bonus'), ('tbr_completion', 'Personal TBR completion bonus'), ('game_reward', 'Game/manual reward')], max_length=24)),
                ('source_reference', models.CharField(max_length=120)),
                ('source_label', models.CharField(max_length=200)),
                ('source_context', models.TextField(blank=True)),
                ('amount', models.PositiveIntegerField()),
                ('effective_date', models.DateField()),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_system_generated', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_modifier_provenance', to=settings.AUTH_USER_MODEL)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modifier_provenance', to='core.challengemonth')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modifier_provenance', to='core.membership')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modifier_provenance', to='core.booksubmission')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_modifier_provenance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['effective_date', 'pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='modifier_provenance_amount_positive'), models.CheckConstraint(condition=models.Q(('source_reference', ''), _negated=True), name='modifier_provenance_source_present'), models.UniqueConstraint(fields=('source_type', 'source_reference'), name='unique_modifier_provenance_source')],
            },
        ),
        migrations.RunPython(backfill_modifier_provenance, migrations.RunPython.noop),
    ]
