# Generated by Django 5.2.17 on 2026-08-28 16:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0043_modifier_provenance_foundation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="challengemonth",
            name="games_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("advertised_bonus_pages", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("month", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="games", to="core.challengemonth")),
            ],
            options={"ordering": ["starts_at", "name", "pk"]},
        ),
        migrations.CreateModel(
            name="GameRewardApplication",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.PositiveIntegerField()),
                ("target_type", models.CharField(choices=[("reader", "Reader"), ("team", "Team"), ("challenge", "Challenge-wide")], max_length=12)),
                ("target_label", models.CharField(max_length=200)),
                ("game_name_snapshot", models.CharField(max_length=120)),
                ("advertised_bonus_pages_snapshot", models.PositiveIntegerField()),
                ("reason", models.TextField()),
                ("applied_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("idempotency_key", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("is_voided", models.BooleanField(default=False)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                ("void_reason", models.TextField(blank=True)),
                ("applied_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="applied_game_rewards", to=settings.AUTH_USER_MODEL)),
                ("game", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="reward_applications", to="core.game")),
                ("target_participant", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="targeted_game_reward_applications", to="core.membership")),
                ("target_team", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="game_reward_applications", to="core.team")),
                ("voided_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="voided_game_rewards", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["applied_at", "pk"]},
        ),
        migrations.CreateModel(
            name="GameRewardRecipient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("application", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="recipients", to="core.gamerewardapplication")),
                ("participant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="game_reward_recipients", to="core.membership")),
                ("provenance", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="game_reward_recipient", to="core.modifierprovenance")),
            ],
            options={"ordering": ["application_id", "participant_id"]},
        ),
        migrations.AddConstraint(model_name="game", constraint=models.UniqueConstraint(fields=("month", "name"), name="unique_game_name_per_challenge")),
        migrations.AddConstraint(model_name="game", constraint=models.CheckConstraint(condition=models.Q(("advertised_bonus_pages__gt", 0)), name="game_advertised_bonus_positive")),
        migrations.AddConstraint(model_name="game", constraint=models.CheckConstraint(condition=models.Q(("ends_at__gt", models.F("starts_at"))), name="game_end_after_start")),
        migrations.AddConstraint(model_name="gamerewardapplication", constraint=models.CheckConstraint(condition=models.Q(("amount__gt", 0)), name="game_reward_amount_positive")),
        migrations.AddConstraint(model_name="gamerewardapplication", constraint=models.CheckConstraint(condition=models.Q(("advertised_bonus_pages_snapshot__gt", 0)), name="game_reward_advertised_snapshot_positive")),
        migrations.AddConstraint(model_name="gamerewardapplication", constraint=models.CheckConstraint(condition=models.Q(("amount__lte", models.F("advertised_bonus_pages_snapshot"))), name="game_reward_amount_within_advertised")),
        migrations.AddConstraint(model_name="gamerewardapplication", constraint=models.CheckConstraint(condition=~models.Q(target_label=""), name="game_reward_target_label_present")),
        migrations.AddConstraint(model_name="gamerewardapplication", constraint=models.CheckConstraint(condition=~models.Q(game_name_snapshot=""), name="game_reward_game_name_present")),
        migrations.AddConstraint(model_name="gamerewardapplication", constraint=models.CheckConstraint(condition=~models.Q(reason=""), name="game_reward_reason_present")),
        migrations.AddConstraint(
            model_name="gamerewardapplication",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(target_type="reader", target_participant__isnull=False, target_team__isnull=True)
                    | models.Q(target_type="team", target_participant__isnull=True, target_team__isnull=False)
                    | models.Q(target_type="challenge", target_participant__isnull=True, target_team__isnull=True)
                ),
                name="game_reward_target_coherent",
            ),
        ),
        migrations.AddConstraint(
            model_name="gamerewardapplication",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(is_voided=False, voided_at__isnull=True, voided_by__isnull=True, void_reason="")
                    | (models.Q(is_voided=True, voided_at__isnull=False) & ~models.Q(void_reason=""))
                ),
                name="game_reward_void_state_coherent",
            ),
        ),
        migrations.AddConstraint(model_name="gamerewardrecipient", constraint=models.UniqueConstraint(fields=("application", "participant"), name="unique_game_reward_recipient")),
    ]
