# Generated by Django 5.2.17 on 2026-08-29 01:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_games_schema_foundation'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengemonth',
            name='botm_completion_bonus_pages',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='challengemonth',
            name='botm_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='BotmBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('title_snapshot', models.CharField(max_length=300)),
                ('author_snapshot', models.CharField(max_length=300)),
                ('page_count_snapshot', models.PositiveIntegerField()),
                ('cover_url_snapshot', models.URLField(blank=True, max_length=1000)),
                ('source_url_snapshot', models.URLField(blank=True, max_length=1000)),
                ('normalized_title', models.CharField(editable=False, max_length=300)),
                ('normalized_author', models.CharField(editable=False, max_length=300)),
                ('bonus_pages', models.PositiveIntegerField(default=0)),
                ('is_retired', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalog_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='botm_books', to='core.catalogbook')),
                ('catalog_edition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='botm_books', to='core.catalogedition')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='botm_books', to='core.challengemonth')),
            ],
            options={
                'ordering': ['position', 'pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('position__gte', 1), ('position__lte', 9)), name='botm_position_1_to_9'), models.CheckConstraint(condition=models.Q(('page_count_snapshot__gt', 0)), name='botm_page_count_positive'), models.CheckConstraint(condition=models.Q(('bonus_pages__gte', 0)), name='botm_bonus_nonnegative'), models.UniqueConstraint(condition=models.Q(('is_retired', False)), fields=('month', 'position'), name='unique_active_botm_position'), models.UniqueConstraint(condition=models.Q(('catalog_book__isnull', False), ('is_retired', False)), fields=('month', 'catalog_book'), name='unique_active_botm_catalog_book'), models.UniqueConstraint(condition=models.Q(('catalog_book__isnull', True), ('is_retired', False)), fields=('month', 'normalized_title', 'normalized_author'), name='unique_active_manual_botm_identity')],
            },
        ),
    ]
