# Generated by Django 5.2.17 on 2026-08-29 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_botm_matching_foundation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotmCompletionAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_set_fingerprint', models.CharField(max_length=64)),
                ('configured_book_count', models.PositiveSmallIntegerField()),
                ('bonus_amount_snapshot', models.PositiveIntegerField(default=0)),
                ('qualified_at', models.DateTimeField()),
                ('last_qualified_at', models.DateTimeField()),
                ('effective_date', models.DateField()),
                ('is_qualifying', models.BooleanField(default=True)),
                ('inactivated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='botm_completion_awards', to='core.challengemonth')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='botm_completion_awards', to='core.membership')),
            ],
            options={
                'ordering': ['-qualified_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='BotmCompletionAwardBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_snapshot', models.PositiveSmallIntegerField()),
                ('title_snapshot', models.CharField(max_length=300)),
                ('author_snapshot', models.CharField(max_length=300)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configured_books', to='core.botmcompletionaward')),
                ('botm_book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='completion_award_snapshots', to='core.botmbook')),
            ],
            options={
                'ordering': ['position_snapshot', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='botmcompletionaward',
            constraint=models.CheckConstraint(condition=models.Q(('configured_book_count__gte', 1)), name='botm_completion_count_positive'),
        ),
        migrations.AddConstraint(
            model_name='botmcompletionaward',
            constraint=models.CheckConstraint(condition=models.Q(('bonus_amount_snapshot__gte', 0)), name='botm_completion_bonus_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='botmcompletionaward',
            constraint=models.UniqueConstraint(fields=('month', 'participant', 'completion_set_fingerprint'), name='unique_botm_completion_set_per_reader'),
        ),
        migrations.AddConstraint(
            model_name='botmcompletionawardbook',
            constraint=models.UniqueConstraint(fields=('award', 'botm_book'), name='unique_botm_book_per_completion_award'),
        ),
        migrations.AddConstraint(
            model_name='botmcompletionawardbook',
            constraint=models.UniqueConstraint(fields=('award', 'position_snapshot'), name='unique_botm_position_per_completion_award'),
        ),
    ]
