# Generated by Django 5.2.17 on 2026-08-30 13:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_readerhardcoverconnection'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalTBR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Personal TBR',
                'verbose_name_plural': 'Personal TBRs',
            },
        ),
        migrations.CreateModel(
            name='PersonalTBRBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('title_snapshot', models.CharField(max_length=300)),
                ('author_snapshot', models.CharField(max_length=300)),
                ('page_count_snapshot', models.PositiveIntegerField(blank=True, null=True)),
                ('cover_url_snapshot', models.URLField(blank=True, max_length=1000)),
                ('source_url_snapshot', models.URLField(blank=True, max_length=1000)),
                ('normalized_title', models.CharField(editable=False, max_length=300)),
                ('normalized_author', models.CharField(editable=False, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['position', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='challengemonth',
            name='tbr_book_bonus_pages',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='challengemonth',
            name='tbr_completion_bonus_pages',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='challengemonth',
            name='tbr_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='challengemonth',
            constraint=models.CheckConstraint(condition=models.Q(('tbr_book_bonus_pages__gte', 0)), name='tbr_book_bonus_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='challengemonth',
            constraint=models.CheckConstraint(condition=models.Q(('tbr_completion_bonus_pages__gte', 0)), name='tbr_completion_bonus_nonnegative'),
        ),
        migrations.AddField(
            model_name='personaltbr',
            name='enrollment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_tbr', to='core.monthenrollment'),
        ),
        migrations.AddField(
            model_name='personaltbrbook',
            name='catalog_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personal_tbr_books', to='core.catalogbook'),
        ),
        migrations.AddField(
            model_name='personaltbrbook',
            name='catalog_edition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personal_tbr_books', to='core.catalogedition'),
        ),
        migrations.AddField(
            model_name='personaltbrbook',
            name='personal_tbr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='core.personaltbr'),
        ),
        migrations.AddConstraint(
            model_name='personaltbrbook',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 1), ('position__lte', 9)), name='personal_tbr_position_1_to_9'),
        ),
        migrations.AddConstraint(
            model_name='personaltbrbook',
            constraint=models.CheckConstraint(condition=models.Q(('page_count_snapshot__isnull', True), ('page_count_snapshot__gt', 0), _connector='OR'), name='personal_tbr_page_count_positive'),
        ),
        migrations.AddConstraint(
            model_name='personaltbrbook',
            constraint=models.CheckConstraint(condition=models.Q(('normalized_title', ''), _negated=True), name='personal_tbr_title_present'),
        ),
        migrations.AddConstraint(
            model_name='personaltbrbook',
            constraint=models.CheckConstraint(condition=models.Q(('normalized_author', ''), _negated=True), name='personal_tbr_author_present'),
        ),
        migrations.AddConstraint(
            model_name='personaltbrbook',
            constraint=models.UniqueConstraint(fields=('personal_tbr', 'position'), name='unique_personal_tbr_position'),
        ),
        migrations.AddConstraint(
            model_name='personaltbrbook',
            constraint=models.UniqueConstraint(condition=models.Q(('catalog_book__isnull', False)), fields=('personal_tbr', 'catalog_book'), name='unique_personal_tbr_catalog_book'),
        ),
        migrations.AddConstraint(
            model_name='personaltbrbook',
            constraint=models.UniqueConstraint(fields=('personal_tbr', 'normalized_title', 'normalized_author'), name='unique_personal_tbr_identity'),
        ),
    ]
