# Generated by Django 5.2.17 on 2026-08-30 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_personaltbr_personaltbrbook_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalTBRMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('catalog_work', 'Catalog work'), ('normalized_title_author', 'Normalized title and author'), ('manual_review', 'Manual review')], max_length=32)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('pending_review', 'Pending review'), ('rejected', 'Rejected')], max_length=20)),
                ('is_qualifying', models.BooleanField(default=False)),
                ('tbr_title_snapshot', models.CharField(max_length=300)),
                ('tbr_author_snapshot', models.CharField(max_length=300)),
                ('tbr_catalog_identity', models.CharField(blank=True, max_length=160)),
                ('submission_title_snapshot', models.CharField(max_length=300)),
                ('submission_author_snapshot', models.CharField(max_length=200)),
                ('submission_catalog_identity', models.CharField(blank=True, max_length=160)),
                ('normalized_title_evidence', models.CharField(blank=True, max_length=300)),
                ('normalized_author_evidence', models.CharField(blank=True, max_length=300)),
                ('evidence_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal_tbr_matches', to='core.challengemonth')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal_tbr_matches', to='core.membership')),
                ('personal_tbr_book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='core.personaltbrbook')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_personal_tbr_matches', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal_tbr_matches', to='core.booksubmission')),
            ],
            options={
                'ordering': ['-updated_at', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('personal_tbr_book', 'submission'), name='unique_personal_tbr_match_relationship'), models.UniqueConstraint(condition=models.Q(('is_qualifying', True), ('status', 'confirmed')), fields=('submission',), name='one_qualifying_tbr_per_submission'), models.UniqueConstraint(condition=models.Q(('is_qualifying', True), ('status', 'confirmed')), fields=('personal_tbr_book',), name='one_qualifying_submission_per_tbr_book')],
            },
        ),
    ]
