# Generated by Django 5.2.17 on 2026-08-30 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_personal_tbr_matching_foundation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalTBRCompletionAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_set_fingerprint', models.CharField(max_length=64)),
                ('configured_book_count', models.PositiveSmallIntegerField(default=9)),
                ('bonus_amount_snapshot', models.PositiveIntegerField(default=0)),
                ('qualified_at', models.DateTimeField()),
                ('last_qualified_at', models.DateTimeField()),
                ('effective_date', models.DateField()),
                ('is_qualifying', models.BooleanField(default=True)),
                ('inactivated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal_tbr_completion_awards', to='core.challengemonth')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal_tbr_completion_awards', to='core.membership')),
                ('personal_tbr', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='completion_award', to='core.personaltbr')),
            ],
            options={
                'ordering': ['-qualified_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='PersonalTBRCompletionAwardBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_snapshot', models.PositiveSmallIntegerField()),
                ('title_snapshot', models.CharField(max_length=300)),
                ('author_snapshot', models.CharField(max_length=300)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configured_books', to='core.personaltbrcompletionaward')),
                ('personal_tbr_book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='completion_award_snapshots', to='core.personaltbrbook')),
            ],
            options={
                'ordering': ['position_snapshot', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='personaltbrcompletionaward',
            constraint=models.CheckConstraint(condition=models.Q(('configured_book_count', 9)), name='personal_tbr_completion_count_nine'),
        ),
        migrations.AddConstraint(
            model_name='personaltbrcompletionaward',
            constraint=models.CheckConstraint(condition=models.Q(('bonus_amount_snapshot__gte', 0)), name='personal_tbr_completion_bonus_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='personaltbrcompletionawardbook',
            constraint=models.UniqueConstraint(fields=('award', 'personal_tbr_book'), name='unique_tbr_book_per_completion_award'),
        ),
        migrations.AddConstraint(
            model_name='personaltbrcompletionawardbook',
            constraint=models.UniqueConstraint(fields=('award', 'position_snapshot'), name='unique_tbr_position_per_completion_award'),
        ),
    ]
