# Generated by Django 5.2.17 on 2026-08-31 12:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_personal_tbr_completion_awards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tier', models.PositiveSmallIntegerField(choices=[(1, 'Tier 1 — Routine correction'), (2, 'Tier 2 — Destructive recovery'), (3, 'Tier 3 — Emergency recovery')])),
                ('action', models.CharField(max_length=120)),
                ('target_type', models.CharField(max_length=120)),
                ('target_id', models.CharField(blank=True, max_length=120)),
                ('target_label', models.CharField(max_length=300)),
                ('reason', models.TextField(blank=True)),
                ('confirmation_method', models.CharField(blank=True, max_length=120)),
                ('impact', models.JSONField(blank=True, default=dict)),
                ('before_state', models.JSONField(blank=True, default=dict)),
                ('after_state', models.JSONField(blank=True, default=dict)),
                ('result', models.CharField(choices=[('succeeded', 'Succeeded'), ('failed', 'Failed')], max_length=12)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_operations', to=settings.AUTH_USER_MODEL)),
                ('challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_operations', to='core.challengemonth')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_operations', to='core.readinggroup')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='recoveryoperation',
            constraint=models.CheckConstraint(condition=models.Q(('tier__in', [1, 2, 3])), name='recovery_operation_tier_valid'),
        ),
    ]
