# Generated by Django 5.2.17 on 2026-08-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_recovery_operation_ledger"),
    ]

    operations = [
        migrations.AddField(
            model_name="progresscheckpoint",
            name="recovery_hold",
            field=models.BooleanField(
                default=False,
                help_text="Platform recovery has paused automatic checkpoint processing until explicit release.",
            ),
        ),
    ]
