# Generated by Django 5.2.17 on 2026-09-01 19:48

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_progresscheckpoint_recovery_hold'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardcoverOAuthApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.BooleanField(default=True, editable=False, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('client_id', models.CharField(blank=True, max_length=255)),
                ('encrypted_client_secret', models.TextField(blank=True)),
                ('configured_scopes', models.JSONField(default=core.models.default_hardcover_oauth_scopes, editable=False)),
                ('configured_website_url', models.URLField(blank=True, max_length=500)),
                ('configured_redirect_uri', models.URLField(blank=True, max_length=600)),
                ('configured_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_tested_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_valid', models.BooleanField(default=False, editable=False)),
                ('last_error', models.CharField(blank=True, editable=False, max_length=300)),
            ],
        ),
        migrations.AddConstraint(
            model_name='hardcoveroauthapplication',
            constraint=models.CheckConstraint(condition=models.Q(('singleton_key', True)), name='hardcover_oauth_application_singleton_true'),
        ),
        migrations.AddField(
            model_name='readerhardcoverconnection',
            name='connection_method',
            field=models.CharField(choices=[('api_key', 'Scoped API key'), ('oauth', 'OAuth')], default='api_key', max_length=20),
        ),
    ]
