# Generated by Django 5.2.17 on 2026-09-01 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_hardcover_sync_foundation'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardcoversyncoutbox',
            name='provider_book_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hardcoversyncoutbox',
            name='provider_user_book_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hardcoversyncoutbox',
            name='result_detail',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='hardcoversyncprovenance',
            name='provider_book_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hardcoversyncprovenance',
            name='result_detail',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
