# Generated by Django 5.2.17 on 2026-09-02 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_hardcover_completed_book_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardcoversyncoutbox',
            name='library_result_detail',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='hardcoversyncoutbox',
            name='occurrence_result_detail',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='hardcoversyncoutbox',
            name='provider_read_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hardcoversyncprovenance',
            name='library_result_detail',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='hardcoversyncprovenance',
            name='occurrence_result_detail',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='hardcoversyncprovenance',
            name='provider_read_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
